import { theme, type ThemeConfig } from 'antd';

export const staffThemeTokens = {
  background: '#f6f8fb',
  backgroundAccent: '#f8fbff',
  surface1: '#ffffff',
  surface2: '#f1f5f9',
  surface3: '#eef2f7',
  border: '#d8e0ea',
  borderSubtle: '#e5eaf1',
  textPrimary: '#111827',
  textSecondary: '#4b5563',
  textTertiary: '#6b7280',
  disabled: '#9ca3af',
  primary: '#2563eb',
  primaryHover: '#1d4ed8',
  info: '#0284c7',
  success: '#16a34a',
  warning: '#d97706',
  danger: '#dc2626',
  analytics: '#7c3aed',
  // New Operational Status tokens
  pending: '#eab308',
  offline: '#64748b',
  syncing: '#3b82f6',
  conflict: '#f97316',
  criticalAlert: '#991b1b',
} as const;

export const staffAntTheme: ThemeConfig = {
  algorithm: [theme.defaultAlgorithm, theme.compactAlgorithm],
  token: {
    colorPrimary: staffThemeTokens.primary,
    colorInfo: staffThemeTokens.info,
    colorSuccess: staffThemeTokens.success,
    colorWarning: staffThemeTokens.warning,
    colorError: staffThemeTokens.danger,
    colorBgLayout: staffThemeTokens.background,
    colorBgContainer: staffThemeTokens.surface1,
    colorBgElevated: staffThemeTokens.surface2,
    colorBorder: staffThemeTokens.border,
    colorBorderSecondary: staffThemeTokens.borderSubtle,
    colorText: staffThemeTokens.textPrimary,
    colorTextSecondary: staffThemeTokens.textSecondary,
    colorTextTertiary: staffThemeTokens.textTertiary,
    colorTextDisabled: staffThemeTokens.disabled,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    controlHeight: 44,
    controlHeightSM: 36,
    controlHeightLG: 52,
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 13,
    wireframe: false,
  },
  components: {
    Alert: {
      colorInfoBg: 'rgba(37, 99, 235, 0.1)',
      colorSuccessBg: 'rgba(22, 163, 74, 0.1)',
      colorWarningBg: 'rgba(245, 158, 11, 0.12)',
      colorErrorBg: 'rgba(220, 38, 38, 0.1)',
    },
    Button: {
      borderRadius: 6,
      controlHeight: 44,
      controlHeightLG: 52,
      fontWeight: 600,
      primaryShadow: 'none',
    },
    Card: {
      borderRadiusLG: 14,
      colorBgContainer: staffThemeTokens.surface1,
      colorBorderSecondary: staffThemeTokens.border,
      paddingLG: 16,
    },
    Drawer: {
      colorBgElevated: staffThemeTokens.surface1,
    },
    Input: {
      activeBorderColor: staffThemeTokens.primary,
      hoverBorderColor: staffThemeTokens.primaryHover,
    },
    Layout: {
      bodyBg: staffThemeTokens.background,
      headerBg: staffThemeTokens.surface1,
      siderBg: staffThemeTokens.surface1,
    },
    Menu: {
      itemBg: staffThemeTokens.surface1,
      subMenuItemBg: staffThemeTokens.surface1,
      itemHoverBg: 'rgba(37, 99, 235, 0.08)',
      itemActiveBg: 'rgba(37, 99, 235, 0.1)',
      itemSelectedBg: 'rgba(37, 99, 235, 0.12)',
      itemSelectedColor: staffThemeTokens.primary,
    },
    Modal: {
      contentBg: staffThemeTokens.surface1,
      headerBg: staffThemeTokens.surface1,
    },
    Select: {
      optionSelectedBg: 'rgba(37, 99, 235, 0.12)',
    },
    Table: {
      borderColor: staffThemeTokens.border,
      headerBg: staffThemeTokens.surface2,
      headerColor: staffThemeTokens.textSecondary,
      rowHoverBg: 'rgba(37, 99, 235, 0.08)',
    },
    Tabs: {
      itemActiveColor: staffThemeTokens.textPrimary,
      itemSelectedColor: staffThemeTokens.primary,
      inkBarColor: staffThemeTokens.primary,
    },
  },
};
