import { theme, type ThemeConfig } from 'antd';

export const staffThemeTokens = {
  background: '#f6f8fb',
  backgroundAccent: '#eef4f9',
  surface1: '#ffffff',
  surface2: '#f1f5f9',
  surface3: '#e6edf5',
  border: '#d8e2ee',
  borderSubtle: '#e5edf6',
  textPrimary: '#172033',
  textSecondary: '#506176',
  textTertiary: '#74839a',
  disabled: '#9aa8ba',
  primary: '#2563eb',
  primaryHover: '#1d4ed8',
  info: '#2563eb',
  success: '#16a34a',
  warning: '#f59e0b',
  danger: '#dc2626',
  analytics: '#d946ef',
} as const;

export const staffAntTheme: ThemeConfig = {
  algorithm: [theme.defaultAlgorithm, theme.compactAlgorithm],
  token: {
    colorPrimary: staffThemeTokens.primary,
    colorInfo: staffThemeTokens.info,
    colorSuccess: staffThemeTokens.success,
    colorWarning: staffThemeTokens.warning,
    colorError: staffThemeTokens.danger,
    colorBgLayout: staffThemeTokens.background,
    colorBgContainer: staffThemeTokens.surface1,
    colorBgElevated: staffThemeTokens.surface2,
    colorBorder: staffThemeTokens.border,
    colorBorderSecondary: staffThemeTokens.borderSubtle,
    colorText: staffThemeTokens.textPrimary,
    colorTextSecondary: staffThemeTokens.textSecondary,
    colorTextTertiary: staffThemeTokens.textTertiary,
    colorTextDisabled: staffThemeTokens.disabled,
    borderRadius: 10,
    borderRadiusLG: 14,
    borderRadiusSM: 8,
    controlHeight: 36,
    controlHeightSM: 30,
    controlHeightLG: 44,
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 13,
    wireframe: false,
  },
  components: {
    Alert: {
      colorInfoBg: 'rgba(37, 99, 235, 0.1)',
      colorSuccessBg: 'rgba(22, 163, 74, 0.1)',
      colorWarningBg: 'rgba(245, 158, 11, 0.12)',
      colorErrorBg: 'rgba(220, 38, 38, 0.1)',
    },
    Button: {
      borderRadius: 10,
      controlHeight: 36,
      controlHeightLG: 44,
      fontWeight: 700,
      primaryShadow: '0 10px 22px rgba(37, 99, 235, 0.2)',
    },
    Card: {
      borderRadiusLG: 14,
      colorBgContainer: staffThemeTokens.surface1,
      colorBorderSecondary: staffThemeTokens.border,
      paddingLG: 16,
    },
    Drawer: {
      colorBgElevated: staffThemeTokens.surface1,
    },
    Input: {
      activeBorderColor: staffThemeTokens.primary,
      hoverBorderColor: staffThemeTokens.primaryHover,
    },
    Layout: {
      bodyBg: staffThemeTokens.background,
      headerBg: 'rgba(255, 255, 255, 0.94)',
      siderBg: staffThemeTokens.surface1,
    },
    Menu: {
      darkItemBg: staffThemeTokens.surface1,
      darkSubMenuItemBg: staffThemeTokens.surface1,
      darkItemSelectedBg: 'rgba(37, 99, 235, 0.12)',
      darkItemSelectedColor: staffThemeTokens.textPrimary,
    },
    Modal: {
      contentBg: staffThemeTokens.surface1,
      headerBg: staffThemeTokens.surface1,
    },
    Select: {
      optionSelectedBg: 'rgba(37, 99, 235, 0.12)',
    },
    Table: {
      borderColor: staffThemeTokens.border,
      headerBg: staffThemeTokens.surface2,
      headerColor: staffThemeTokens.textSecondary,
      rowHoverBg: 'rgba(37, 99, 235, 0.08)',
    },
    Tabs: {
      itemActiveColor: staffThemeTokens.textPrimary,
      itemSelectedColor: staffThemeTokens.primary,
      inkBarColor: staffThemeTokens.primary,
    },
  },
};
