START TRANSACTION;

CREATE TABLE IF NOT EXISTS `reservation_bill_payment_sessions` (
  `bill_payment_session_id` int unsigned NOT NULL AUTO_INCREMENT,
  `reservation_id` int unsigned NOT NULL,
  `order_id` int unsigned DEFAULT NULL,
  `customer_user_id` int unsigned NOT NULL,
  `linked_payment_id` int unsigned DEFAULT NULL,
  `provider_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'simulated',
  `provider_session_code` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_payment_code` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_method` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(14,2) NOT NULL,
  `currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'VND',
  `session_status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Created',
  `settlement_status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NotApplied',
  `failure_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `failure_message` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_payload_json` json DEFAULT NULL,
  `idempotency_key` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_expires_at` datetime(6) DEFAULT NULL,
  `last_reconciled_at` datetime(6) DEFAULT NULL,
  `confirmed_at` datetime(6) DEFAULT NULL,
  `failed_at` datetime(6) DEFAULT NULL,
  `cancelled_at` datetime(6) DEFAULT NULL,
  `expired_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `created_by` int unsigned DEFAULT NULL,
  `updated_by` int unsigned DEFAULT NULL,
  `row_version` bigint unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`bill_payment_session_id`),
  UNIQUE KEY `uq_reservation_bill_payment_sessions__reservation_id__i_2839be4a` (`reservation_id`,`idempotency_key`),
  UNIQUE KEY `uq_reservation_bill_payment_sessions__provider_code__pr_5c790f76` (`provider_code`,`provider_session_code`),
  UNIQUE KEY `uq_reservation_bill_payment_sessions__linked_payment_id` (`linked_payment_id`),
  KEY `fk_reservation_bill_payment_sessions__reservation_id__r_a8d6b53e` (`reservation_id`),
  KEY `fk_reservation_bill_payment_sessions__order_id__reserva_ce14f420` (`order_id`),
  KEY `fk_reservation_bill_payment_sessions__customer_user_id__users` (`customer_user_id`),
  KEY `idx_reservation_bill_payment_sessions__reservation_id___b47ad219` (`reservation_id`,`session_status`),
  KEY `idx_reservation_bill_payment_sessions__customer_user_id_69f85b0a` (`customer_user_id`,`created_at`),
  KEY `idx_reservation_bill_payment_sessions__settlement_status` (`settlement_status`),
  KEY `idx_reservation_bill_payment_sessions__updated_by` (`updated_by`),
  CONSTRAINT `fk_reservation_bill_payment_sessions__reservation_id__r_a8d6b53e` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`reservation_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_bill_payment_sessions__order_id__reserva_ce14f420` FOREIGN KEY (`order_id`) REFERENCES `reservation_orders` (`order_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_bill_payment_sessions__customer_user_id__users` FOREIGN KEY (`customer_user_id`) REFERENCES `users` (`user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_bill_payment_sessions__linked_payment_id_29c6b2c1` FOREIGN KEY (`linked_payment_id`) REFERENCES `payments` (`payment_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_bill_payment_sessions__created_by__users` FOREIGN KEY (`created_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_bill_payment_sessions__updated_by__users` FOREIGN KEY (`updated_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `chk_reservation_bill_payment_sessions__money_nonneg` CHECK (`amount` >= 0),
  CONSTRAINT `chk_reservation_bill_payment_sessions__session_status` CHECK (`session_status` in ('Created','Pending','Succeeded','Failed','Cancelled','Expired')),
  CONSTRAINT `chk_reservation_bill_payment_sessions__settlement_status` CHECK (`settlement_status` in ('NotApplied','Applied','Skipped'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
