CREATE TABLE IF NOT EXISTS `reporting_daily_sales_snapshots` (
  `snapshot_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` int unsigned NOT NULL,
  `business_date` date NOT NULL,
  `currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'VND',
  `billed_reservation_count` int unsigned NOT NULL DEFAULT '0',
  `billed_guest_count` int unsigned NOT NULL DEFAULT '0',
  `gross_bill_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `billed_total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `invoice_issued_count` int unsigned NOT NULL DEFAULT '0',
  `invoiced_total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `invoiced_tax_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `payment_row_count` int unsigned NOT NULL DEFAULT '0',
  `refund_row_count` int unsigned NOT NULL DEFAULT '0',
  `captured_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `refunded_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `net_paid_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `deposit_net_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `final_net_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `cashier_shift_closed_count` int unsigned NOT NULL DEFAULT '0',
  `cash_discrepancy_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `refreshed_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uq_reporting_daily_sales_snapshots__branch_id__business_7ee7b06b` (`branch_id`,`business_date`,`currency`),
  KEY `idx_reporting_daily_sales_snapshots__business_date__branch_id` (`business_date`,`branch_id`),
  CONSTRAINT `fk_reporting_daily_sales_snapshots__branch_id__branches` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`branch_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_reporting_daily_sales_snapshots__money_nonneg` CHECK (((`gross_bill_amount` >= 0) and (`discount_amount` >= 0) and (`billed_total_amount` >= 0) and (`invoiced_total_amount` >= 0) and (`invoiced_tax_amount` >= 0) and (`captured_amount` >= 0) and (`refunded_amount` >= 0) and (`net_paid_amount` >= 0) and (`deposit_net_amount` >= 0) and (`final_net_amount` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reporting_daily_operation_snapshots` (
  `snapshot_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` int unsigned NOT NULL,
  `business_date` date NOT NULL,
  `scheduled_reservation_count` int unsigned NOT NULL DEFAULT '0',
  `scheduled_guest_count` int unsigned NOT NULL DEFAULT '0',
  `scheduled_minutes_total` int unsigned NOT NULL DEFAULT '0',
  `checked_in_count` int unsigned NOT NULL DEFAULT '0',
  `completed_count` int unsigned NOT NULL DEFAULT '0',
  `cancelled_count` int unsigned NOT NULL DEFAULT '0',
  `no_show_count` int unsigned NOT NULL DEFAULT '0',
  `turn_count` int unsigned NOT NULL DEFAULT '0',
  `turn_minutes_total` int unsigned NOT NULL DEFAULT '0',
  `waiting_list_created_count` int unsigned NOT NULL DEFAULT '0',
  `waiting_list_notified_count` int unsigned NOT NULL DEFAULT '0',
  `waiting_list_seated_count` int unsigned NOT NULL DEFAULT '0',
  `waiting_list_cancelled_count` int unsigned NOT NULL DEFAULT '0',
  `waiting_list_confirmed_arrival_count` int unsigned NOT NULL DEFAULT '0',
  `refreshed_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uq_reporting_daily_operation_snapshots__branch_id__business_date` (`branch_id`,`business_date`),
  KEY `idx_reporting_daily_operation_snapshots__business_date__80d8b18a` (`business_date`,`branch_id`),
  CONSTRAINT `fk_reporting_daily_operation_snapshots__branch_id__branches` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`branch_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `reporting_daily_inventory_movement_snapshots` (
  `snapshot_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` int unsigned NOT NULL,
  `business_date` date NOT NULL,
  `ingredient_id` int unsigned NOT NULL,
  `unit_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `movement_count` int unsigned NOT NULL DEFAULT '0',
  `purchase_receipt_movement_count` int unsigned NOT NULL DEFAULT '0',
  `stock_in_quantity` decimal(14,3) NOT NULL DEFAULT '0.000',
  `stock_out_quantity` decimal(14,3) NOT NULL DEFAULT '0.000',
  `adjustment_increase_quantity` decimal(14,3) NOT NULL DEFAULT '0.000',
  `adjustment_decrease_quantity` decimal(14,3) NOT NULL DEFAULT '0.000',
  `wastage_quantity` decimal(14,3) NOT NULL DEFAULT '0.000',
  `net_quantity_delta` decimal(14,3) NOT NULL DEFAULT '0.000',
  `last_movement_at` datetime(6) DEFAULT NULL,
  `refreshed_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uq_reporting_daily_inventory_movement_snapshots__branch_63746fdf` (`branch_id`,`business_date`,`ingredient_id`,`unit_code`),
  KEY `idx_reporting_daily_inventory_movement_snapshots__busin_d77c75b1` (`business_date`,`branch_id`,`ingredient_id`),
  CONSTRAINT `fk_reporting_daily_inventory_movement_snapshots__branch_88f21726` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`branch_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_reporting_daily_inventory_movement_snapshots__ingred_20ec5e09` FOREIGN KEY (`ingredient_id`) REFERENCES `ingredients` (`ingredient_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_reporting_daily_inventory_movement_snapshots__quant_525e7578` CHECK (((`stock_in_quantity` >= 0) and (`stock_out_quantity` >= 0) and (`adjustment_increase_quantity` >= 0) and (`adjustment_decrease_quantity` >= 0) and (`wastage_quantity` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
