CREATE TABLE IF NOT EXISTS `billing_invoices` (
  `billing_invoice_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_id` int unsigned NOT NULL,
  `invoice_number` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `invoice_status` enum('Issued','Voided') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Issued',
  `subtotal_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'VND',
  `tax_code` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_name` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_rate_percentage` decimal(6,3) NOT NULL DEFAULT '0.000',
  `prices_include_tax` tinyint(1) NOT NULL DEFAULT '1',
  `taxable_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `seller_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `seller_tax_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `seller_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issued_at` datetime(6) NOT NULL,
  `issued_by` int unsigned DEFAULT NULL,
  `voided_at` datetime(6) DEFAULT NULL,
  `voided_by` int unsigned DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `row_version` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`billing_invoice_id`),
  UNIQUE KEY `uq_billing_invoices__reservation_id` (`reservation_id`),
  UNIQUE KEY `uq_billing_invoices__invoice_number` (`invoice_number`),
  KEY `idx_billing_invoices__invoice_status__issued_at` (`invoice_status`,`issued_at`),
  KEY `idx_billing_invoices__issued_by` (`issued_by`),
  KEY `idx_billing_invoices__voided_by` (`voided_by`),
  CONSTRAINT `fk_billing_invoices__reservation_id__reservations` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`reservation_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_billing_invoices__issued_by__users` FOREIGN KEY (`issued_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `fk_billing_invoices__voided_by__users` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `chk_billing_invoices__money_nonneg` CHECK (((`subtotal_amount` >= 0) and (`discount_amount` >= 0) and (`total_amount` >= 0) and (`taxable_amount` >= 0) and (`tax_amount` >= 0))),
  CONSTRAINT `chk_billing_invoices__summary_consistency` CHECK (((`subtotal_amount` >= `discount_amount`) and (`total_amount` = (`subtotal_amount` - `discount_amount`)) and ((round((`taxable_amount` + `tax_amount`),2)) = `total_amount`))),
  CONSTRAINT `chk_billing_invoices__void_state` CHECK ((((`invoice_status` <> 'Voided') or (`voided_at` is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
