<?php

declare(strict_types=1);

return [
    'artifact_root' => 'storage/app/booking_release/disaster_recovery_drills',
    'backup_root' => 'storage/app/booking_backups',
    'report_sample_limit' => 3,
    'rto_target_minutes' => (int) env('BOOKING_DR_RTO_TARGET_MINUTES', 60),
    'rpo_target_minutes' => (int) env('BOOKING_DR_RPO_TARGET_MINUTES', 1440),
    'safe_target_tokens' => [
        'restore',
        'rehearsal',
        'scratch',
        'drill',
        'sandbox',
        'tmp',
    ],
    'groups' => [
        'backup_artifact_integrity' => 'Backup artifact integrity',
        'restore_execution_safety' => 'Restore execution/safety',
        'schema_integrity' => 'Schema integrity',
        'critical_domain_invariants' => 'Critical domain invariants',
        'data_sample_sanity' => 'Data sample sanity',
        'release_contract_after_restore' => 'Release contract after restore',
    ],
    'modes' => [
        'metadata-verify' => [
            'label' => 'Metadata verification only',
            'description' => 'Validates the backup manifest, checksums, and freshness without touching a restore target.',
            'evidence_level' => 'backup_artifact_verified_only',
            'claim' => 'Backup artifact metadata is internally consistent, but recoverability is not yet proven.',
            'ci_safe' => true,
            'checks' => [
                'backup_manifest_integrity',
                'backup_checksum_inventory',
                'backup_freshness_rpo',
            ],
        ],
        'dry-restore' => [
            'label' => 'Dry restore',
            'description' => 'Validates backup metadata and the restore plan against an isolated target without importing data.',
            'evidence_level' => 'restore_plan_verified_only',
            'claim' => 'The restore path is structurally usable, but a full isolated import has not yet been exercised.',
            'ci_safe' => true,
            'checks' => [
                'backup_manifest_integrity',
                'backup_checksum_inventory',
                'backup_freshness_rpo',
                'restore_target_isolation',
                'restore_dry_plan',
            ],
        ],
        'full-isolated-restore' => [
            'label' => 'Full isolated restore verification',
            'description' => 'Captures the strongest DR evidence by restoring into an isolated target and verifying release/runtime/domain contracts.',
            'evidence_level' => 'full_recoverability_verified',
            'claim' => 'This is the only mode that proves end-to-end recoverability for the selected backup artifact.',
            'ci_safe' => false,
            'checks' => [
                'backup_manifest_integrity',
                'backup_checksum_inventory',
                'backup_freshness_rpo',
                'restore_target_isolation',
                'restore_full_execution',
                'restore_release_contract_sql',
                'restored_target_doctor',
                'restored_target_deploy_postflight',
                'restored_schema_integrity',
                'restored_data_sample_sanity',
                'release_manifest_after_restore',
                'core_ops_gate_after_restore',
                'recovery_objectives_rto',
            ],
        ],
    ],
    'required_tables' => [
        'users',
        'reservations',
        'restaurant_tables',
        'waiting_list',
        'payments',
        'notification_outbox',
    ],
    'sample_tables' => [
        'users' => [
            'columns' => ['user_id', 'role_id', 'created_at'],
            'order_by' => 'user_id',
            'expect_nonzero' => true,
        ],
        'reservations' => [
            'columns' => ['reservation_id', 'status', 'deposit_status', 'start_time', 'created_at'],
            'order_by' => 'reservation_id',
            'expect_nonzero' => false,
        ],
        'restaurant_tables' => [
            'columns' => ['table_id', 'branch_id', 'zone_id', 'capacity'],
            'order_by' => 'table_id',
            'expect_nonzero' => true,
        ],
        'waiting_list' => [
            'columns' => ['waiting_list_id', 'status', 'party_size', 'created_at'],
            'order_by' => 'waiting_list_id',
            'expect_nonzero' => false,
        ],
        'payments' => [
            'columns' => ['payment_id', 'reservation_id', 'payment_type', 'status', 'created_at'],
            'order_by' => 'payment_id',
            'expect_nonzero' => false,
        ],
        'notification_outbox' => [
            'columns' => ['outbox_id', 'channel', 'status', 'template_key', 'created_at'],
            'order_by' => 'outbox_id',
            'expect_nonzero' => false,
        ],
    ],
    'matrix' => [
        [
            'key' => 'backup_manifest_integrity',
            'group' => 'backup_artifact_integrity',
            'label' => 'Backup manifest + artifact integrity',
            'source' => 'backup manifests + BackupRestoreManifest',
            'severity' => 'blocking',
            'pass_criteria' => 'Manifest loads cleanly and at least one schema/full artifact matches its declared checksum and size.',
            'failure_meaning' => 'The selected backup set cannot be trusted as a recovery source.',
            'remediation_hint' => 'Generate a fresh backup artifact set, confirm manifest paths/checksums, then rerun the drill.',
        ],
        [
            'key' => 'backup_checksum_inventory',
            'group' => 'backup_artifact_integrity',
            'label' => 'Checksum inventory completeness',
            'source' => 'checksums.sha256',
            'severity' => 'blocking',
            'pass_criteria' => 'checksums.sha256 exists and contains matching entries for manifest.json plus every referenced restore artifact.',
            'failure_meaning' => 'The artifact bundle is incomplete or tampered, so the backup evidence is not audit-safe.',
            'remediation_hint' => 'Repair or regenerate the checksum inventory together with the backup bundle.',
        ],
        [
            'key' => 'backup_freshness_rpo',
            'group' => 'backup_artifact_integrity',
            'label' => 'Backup freshness vs RPO',
            'source' => 'manifest generated_at_utc',
            'severity' => 'major',
            'pass_criteria' => 'The backup age is within the configured RPO target window.',
            'failure_meaning' => 'The backup may still restore, but it does not satisfy the desired data-loss objective.',
            'remediation_hint' => 'Capture a fresher backup or explicitly accept the larger recovery point before sign-off.',
        ],
        [
            'key' => 'restore_target_isolation',
            'group' => 'restore_execution_safety',
            'label' => 'Isolated target safety boundary',
            'source' => 'booking:dr-drill input guard',
            'severity' => 'blocking',
            'pass_criteria' => 'Dry/full restore modes point to a clearly isolated scratch database and never the live application database.',
            'failure_meaning' => 'Running the drill could damage live data or an unintended environment.',
            'remediation_hint' => 'Use a scratch target database whose name clearly indicates restore/rehearsal/drill scope.',
        ],
        [
            'key' => 'restore_dry_plan',
            'group' => 'restore_execution_safety',
            'label' => 'Dry restore plan',
            'source' => 'tools/mysql/restore_release.php --dry-run',
            'severity' => 'blocking',
            'pass_criteria' => 'restore_release.php accepts the artifact and isolated target plan without import-time blockers.',
            'failure_meaning' => 'The drill cannot reach the import phase reliably on the selected target.',
            'remediation_hint' => 'Fix the restore target guardrail, artifact issue, or restore script failure before attempting a full drill.',
        ],
        [
            'key' => 'restore_full_execution',
            'group' => 'restore_execution_safety',
            'label' => 'Full isolated restore import',
            'source' => 'tools/mysql/restore_release.php',
            'severity' => 'blocking',
            'pass_criteria' => 'restore_release.php completes the isolated import with no blocking step failures.',
            'failure_meaning' => 'The artifact could not be restored into the isolated target cleanly.',
            'remediation_hint' => 'Investigate the restore step outputs, import error, or target-database state before retrying.',
        ],
        [
            'key' => 'restore_release_contract_sql',
            'group' => 'schema_integrity',
            'label' => 'SQL release contract after restore',
            'source' => 'tools/mysql/verify_release_contract.sql',
            'severity' => 'blocking',
            'pass_criteria' => 'verify_release_contract.sql passes against the restored target.',
            'failure_meaning' => 'The restored schema does not satisfy the required release contract.',
            'remediation_hint' => 'Repair the restore artifact or schema bootstrap so the release contract SQL passes.',
        ],
        [
            'key' => 'restored_target_doctor',
            'group' => 'schema_integrity',
            'label' => 'booking:doctor on restored target',
            'source' => 'booking:doctor --strict',
            'severity' => 'blocking',
            'pass_criteria' => 'booking:doctor passes with no restored-target validation or runtime errors.',
            'failure_meaning' => 'The restored target is missing a runtime/schema prerequisite that the release expects.',
            'remediation_hint' => 'Resolve the reported doctor failure and rerun the full isolated restore drill.',
        ],
        [
            'key' => 'restored_target_deploy_postflight',
            'group' => 'critical_domain_invariants',
            'label' => 'booking:deploy-check postflight on restored target',
            'source' => 'booking:deploy-check --mode=postflight --strict',
            'severity' => 'blocking',
            'pass_criteria' => 'Postflight deploy checks find no blocking data, artifact, or operational invariant failures after restore.',
            'failure_meaning' => 'The restored dataset is structurally present but violates critical business/runtime invariants.',
            'remediation_hint' => 'Fix the failing invariant or artifact issue, then rerun the restore drill.',
        ],
        [
            'key' => 'restored_schema_integrity',
            'group' => 'schema_integrity',
            'label' => 'Restored schema inventory',
            'source' => 'Isolated restore schema probe',
            'severity' => 'blocking',
            'pass_criteria' => 'Required tables exist and schema inventory queries complete successfully on the restored target.',
            'failure_meaning' => 'The restore completed, but the restored schema is incomplete or inconsistent.',
            'remediation_hint' => 'Inspect missing tables, incomplete imports, or schema drift before trusting the backup.',
        ],
        [
            'key' => 'restored_data_sample_sanity',
            'group' => 'data_sample_sanity',
            'label' => 'Critical data sample sanity',
            'source' => 'Isolated restore row-count/sample probe',
            'severity' => 'major',
            'pass_criteria' => 'Critical tables can be counted and sampled without query errors; empty anchor tables are explicitly reviewed.',
            'failure_meaning' => 'The restore may be technically complete, but business data looks suspicious or incomplete.',
            'remediation_hint' => 'Inspect the sampled tables and compare against the expected environment state before sign-off.',
        ],
        [
            'key' => 'release_manifest_after_restore',
            'group' => 'release_contract_after_restore',
            'label' => 'Frozen release manifest after restore',
            'source' => 'booking:release-manifest --verify-frozen',
            'severity' => 'blocking',
            'pass_criteria' => 'The current release manifest still matches its frozen snapshot after the drill.',
            'failure_meaning' => 'The release artifact contract is stale or broken, so restored state cannot be certified against the expected release.',
            'remediation_hint' => 'Refresh or repair the frozen release manifest evidence before DR sign-off.',
        ],
        [
            'key' => 'core_ops_gate_after_restore',
            'group' => 'release_contract_after_restore',
            'label' => 'Core ops gate after restore',
            'source' => 'booking:core-ops-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The canonical core ops gate still passes after the restore drill completes.',
            'failure_meaning' => 'The release build regresses critical booking flows, so the recovered target cannot be certified.',
            'remediation_hint' => 'Fix the failing core ops tests before treating the recovered build as release-safe.',
        ],
        [
            'key' => 'recovery_objectives_rto',
            'group' => 'restore_execution_safety',
            'label' => 'Measured RTO vs target',
            'source' => 'booking:dr-drill measured timings',
            'severity' => 'major',
            'pass_criteria' => 'Measured restore + verification time stays within the configured RTO target.',
            'failure_meaning' => 'The drill restored successfully, but the current workflow is slower than the intended recovery objective.',
            'remediation_hint' => 'Measure the slow phase, optimize the restore path, or adjust the documented RTO target with evidence.',
        ],
    ],
];
