<?php

declare(strict_types=1);

return [
    'artifact_root' => 'storage/app/booking_release/launch_readiness',
    'groups' => [
        'environment_runtime' => 'Environment/runtime',
        'api_surface_contract' => 'API surface/contract',
        'booking_core_flows' => 'Booking core flows',
        'performance_resilience' => 'Performance/resilience',
        'payment_checkout_financial_flows' => 'Payment/checkout financial flows',
        'notifications_alerts' => 'Notifications/alerts',
        'release_artifact_integrity' => 'Release artifact integrity',
    ],
    'targets' => [
        'staging' => [
            'label' => 'serious-staging',
        ],
        'limited-production' => [
            'label' => 'limited-production',
        ],
    ],
    'matrix' => [
        [
            'key' => 'doctor_environment_runtime',
            'group' => 'environment_runtime',
            'label' => 'Booking doctor baseline',
            'source' => 'booking:doctor',
            'severity' => 'blocking',
            'pass_criteria' => 'Environment validation has no errors and runtime DB/Redis/scheduler/outbox probes all pass.',
            'failure_meaning' => 'The runtime baseline is unsafe for rollout because a hard prerequisite or live dependency is unhealthy.',
            'remediation_hint' => 'Fix the reported environment/runtime failure, confirm scheduler heartbeat freshness, then rerun booking:doctor and booking:launch-readiness.',
        ],
        [
            'key' => 'deploy_preflight_guardrail',
            'group' => 'environment_runtime',
            'label' => 'Deploy preflight guardrail',
            'source' => 'booking:deploy-check --mode=preflight',
            'severity' => 'blocking',
            'pass_criteria' => 'Preflight deploy checks report no blocking errors across environment, migration, data, artifact, or ops guards.',
            'failure_meaning' => 'The build has preflight drift or invariant failures that can break bootstrap, data safety, or operational readiness.',
            'remediation_hint' => 'Resolve the failing deploy-check sections before attempting staging or limited-production rollout.',
        ],
        [
            'key' => 'route_inventory_contract',
            'group' => 'api_surface_contract',
            'label' => 'Locked route inventory',
            'source' => 'booking:route-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The runtime API surface matches the locked route inventory without action or middleware drift.',
            'failure_meaning' => 'The API surface has drifted from the approved route inventory and may break clients or rollout assumptions.',
            'remediation_hint' => 'Reconcile the route inventory fixture or restore the expected routes before promotion.',
        ],
        [
            'key' => 'openapi_release_contract',
            'group' => 'api_surface_contract',
            'label' => 'Frozen OpenAPI contract artifact',
            'source' => 'booking:release-manifest',
            'severity' => 'blocking',
            'pass_criteria' => 'The release manifest contains a present OpenAPI contract artifact with all required fragments.',
            'failure_meaning' => 'The release bundle is missing the frozen API contract or it has drifted from the required surface.',
            'remediation_hint' => 'Regenerate or repair the OpenAPI release artifact and refresh the release manifest snapshot.',
        ],
        [
            'key' => 'core_ops_flow_gate',
            'group' => 'booking_core_flows',
            'label' => 'Core ops flow suite',
            'source' => 'booking:core-ops-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The canonical core ops suite passes for availability, table holds, reservations, staff floor flows, and waiting-list lifecycle.',
            'failure_meaning' => 'Core booking flows are regressing, so the build is not ready even if route or contract checks stay green.',
            'remediation_hint' => 'Fix the failing core flow tests and rerun the core ops gate before promotion.',
        ],
        [
            'key' => 'round5_financial_gate',
            'group' => 'payment_checkout_financial_flows',
            'label' => 'Round 5 financial suite',
            'source' => 'booking:round5-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The canonical financial suite passes for checkout, refunds, payment provider/webhook, deposit sessions, and bill self-payment.',
            'failure_meaning' => 'Checkout or payment integrity is regressing, so the build is not safe for staged or limited-production rollout.',
            'remediation_hint' => 'Fix the failing financial tests and rerun the Round 5 gate before promotion.',
        ],
        [
            'key' => 'operational_alert_snapshot',
            'group' => 'notifications_alerts',
            'label' => 'Operational alert snapshot',
            'source' => 'booking:alert-check',
            'severity' => 'blocking',
            'pass_criteria' => 'The operational alert snapshot produces no critical alerts; warning alerts are reviewed explicitly.',
            'failure_meaning' => 'Active operational alerts indicate backlog, payment-integrity, or ops-health conditions that could degrade rollout safety.',
            'remediation_hint' => 'Resolve the underlying alert causes, then rerun the launch readiness gate and confirm the alert snapshot is clean.',
        ],
        [
            'key' => 'release_manifest_snapshot',
            'group' => 'release_artifact_integrity',
            'label' => 'Release manifest snapshot health',
            'source' => 'booking:release-manifest',
            'severity' => 'blocking',
            'pass_criteria' => 'The release manifest snapshot completes without missing required artifacts, missing fragments, or patch inventory failures.',
            'failure_meaning' => 'The release bundle is incomplete or inconsistent, so release evidence cannot be trusted.',
            'remediation_hint' => 'Repair the missing artifact, contract fragment, or SQL patch inventory and rerun booking:release-manifest.',
        ],
        [
            'key' => 'release_manifest_frozen',
            'group' => 'release_artifact_integrity',
            'label' => 'Frozen manifest freshness',
            'source' => 'booking:release-manifest --verify-frozen',
            'severity' => 'blocking',
            'pass_criteria' => 'The live release manifest matches the frozen snapshot used for promotion.',
            'failure_meaning' => 'Release evidence has drifted since the frozen manifest snapshot was captured, so packaging or rollout evidence is stale.',
            'remediation_hint' => 'Refresh the frozen release manifest snapshot after regenerating the intended release evidence.',
        ],
        [
            'key' => 'release_package_integrity',
            'group' => 'release_artifact_integrity',
            'label' => 'Immutable release package build',
            'source' => 'booking:package-release --verify-frozen',
            'severity' => 'blocking',
            'pass_criteria' => 'The immutable package builds successfully with sidecar metadata, inventory, and checksums.',
            'failure_meaning' => 'The candidate build cannot be packaged into the release artifact expected for rollout.',
            'remediation_hint' => 'Fix packaging blockers or frozen-manifest issues, then rebuild the immutable package.',
        ],
    ],
    'manual_checks' => [
        [
            'key' => 'uat_scenario_pack_replay',
            'group' => 'booking_core_flows',
            'label' => 'Canonical UAT scenario pack replay',
            'source' => 'UAT/demo scenario pack',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Run the canonical UAT/demo scenario pack against the candidate build and capture operator evidence.',
            'failure_meaning' => 'Automated suites passed, but operator-level end-to-end confirmation for seeded booking flows is still missing.',
            'remediation_hint' => 'Run the UAT bootstrap/scenario scripts and record the evidence in a manual evidence JSON file.',
            'runbook_path' => 'docs/runbooks/uat-demo-scenario-pack.md',
            'operator_commands' => [
                'pwsh -File .\\scripts\\uat\\Bootstrap-UatPack.ps1 -BaseUrl <base-url>',
                'pwsh -File .\\scripts\\uat\\Invoke-UatScenario.ps1 -Scenario all',
            ],
            'operator_notes' => [
                'Capture the scenario summary and record the result under uat_scenario_pack_replay in the manual evidence JSON.',
            ],
        ],
        [
            'key' => 'performance_verification_report',
            'group' => 'performance_resilience',
            'label' => 'Performance verification report',
            'source' => 'booking:performance-verify',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Capture the candidate-specific performance verification report, including the automated load scenarios and any required operator-assisted staging probes.',
            'failure_meaning' => 'The rollout target still lacks candidate-specific performance/resilience evidence for read-heavy and contention-sensitive flows.',
            'remediation_hint' => 'Run booking:performance-verify for the candidate build, archive the report, and record it in the manual evidence JSON before limited production.',
            'runbook_path' => 'docs/runbooks/booking-performance-verification.md',
            'operator_commands' => [
                'php artisan booking:performance-verify --profile=staging --run --base-url=<base-url> --manifest-path=storage/app/uat/scenario-pack.json --promote-baseline',
                'php artisan notifications:outbox-health --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'Archive the candidate-specific performance report and record its outcome under performance_verification_report in the manual evidence JSON.',
            ],
        ],
        [
            'key' => 'payment_provider_external_e2e',
            'group' => 'payment_checkout_financial_flows',
            'label' => 'Real payment-provider callback rehearsal',
            'source' => 'Payment provider / webhook manual rehearsal',
            'required_for' => ['limited-production'],
            'recommended_for' => [],
            'pass_criteria' => 'Validate one end-to-end payment provider callback path against the target integration credentials.',
            'failure_meaning' => 'The automated suite covered adapters and webhook flows, but not the real external provider path for this rollout target.',
            'remediation_hint' => 'Run a real payment-provider callback rehearsal in staging and capture the evidence before limited production.',
            'runbook_path' => 'docs/runbooks/booking-launch-readiness.md',
            'operator_commands' => [
                'php artisan booking:round5-gate --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'Replay one real payment-provider callback against staging credentials, confirm the webhook landed, then record the evidence under payment_provider_external_e2e.',
            ],
        ],
        [
            'key' => 'notification_provider_external_e2e',
            'group' => 'notifications_alerts',
            'label' => 'Real notification delivery rehearsal',
            'source' => 'Notification outbox / provider manual rehearsal',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Validate one end-to-end external notification delivery path against the target mailer/provider and capture both outbox attempt evidence and recipient confirmation.',
            'failure_meaning' => 'Outbox health and retry logic passed, but the rollout target still lacks proof that a real external notification reached the intended recipient.',
            'remediation_hint' => 'Run a staging notification delivery rehearsal against the real email provider and capture the evidence before limited production.',
            'runbook_path' => 'docs/runbooks/notification-platform-v2.md',
            'operator_commands' => [
                'php artisan notifications:outbox-health --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'Trigger one real Email notification against the target mailer/provider, confirm notification_outbox and notification_delivery_attempts, then record the recipient confirmation under notification_provider_external_e2e.',
            ],
        ],
        [
            'key' => 'concurrency_rehearsal',
            'group' => 'booking_core_flows',
            'label' => 'Multi-process concurrency rehearsal',
            'source' => 'Staging concurrency drill',
            'required_for' => ['limited-production'],
            'recommended_for' => [],
            'pass_criteria' => 'Run a Redis/MySQL-backed multi-process rehearsal for table hold and checkout concurrency on staging.',
            'failure_meaning' => 'Single-process automated tests passed, but rollout-level race protection has not been exercised under realistic contention.',
            'remediation_hint' => 'Execute the staging concurrency drill and store the result as manual evidence before limited production.',
            'runbook_path' => 'docs/runbooks/booking-performance-verification.md',
            'operator_commands' => [
                'php artisan booking:performance-verify --profile=staging --run --base-url=<base-url> --scenario=reservation_create_race --scenario=checkout_preview_load',
            ],
            'operator_notes' => [
                'Run the probe while Redis/MySQL contention is injected on staging, archive the report, then record the result under concurrency_rehearsal.',
            ],
        ],
    ],
    'automation_gaps' => [
        [
            'key' => 'uat_pack_operator_evidence',
            'group' => 'booking_core_flows',
            'severity' => 'info',
            'description' => 'The project has a canonical UAT/demo scenario pack, but launch readiness does not auto-run or auto-assert every scenario yet.',
            'recommended_evidence' => 'Store operator evidence from the UAT scenario pack in the manual evidence JSON file.',
        ],
        [
            'key' => 'real_payment_provider_callback',
            'group' => 'payment_checkout_financial_flows',
            'severity' => 'info',
            'description' => 'Round 5 gate validates internal payment flows and adapters, but not a real third-party provider callback against live target credentials.',
            'recommended_evidence' => 'Record one staging callback rehearsal before limited production.',
        ],
        [
            'key' => 'performance_verification_candidate_report',
            'group' => 'performance_resilience',
            'severity' => 'info',
            'description' => 'Local query-budget tests help catch regressions, but they do not replace a candidate-specific booking:performance-verify report with staging probes and resilience evidence.',
            'recommended_evidence' => 'Archive one candidate-specific performance verification report before limited production.',
        ],
        [
            'key' => 'real_notification_delivery',
            'group' => 'notifications_alerts',
            'severity' => 'info',
            'description' => 'Outbox tests and health checks validate enqueue, retry, and alerting, but they do not prove that the real target mailer/provider delivered a live notification.',
            'recommended_evidence' => 'Record one staging notification delivery rehearsal before limited production.',
        ],
        [
            'key' => 'multi_process_contention',
            'group' => 'booking_core_flows',
            'severity' => 'info',
            'description' => 'The automated gates do not simulate multi-process Redis/MySQL contention at rollout load.',
            'recommended_evidence' => 'Attach the result of a staging concurrency rehearsal before limited production.',
        ],
    ],
];
