<?php

declare(strict_types=1);

return [
    'artifact_root' => 'storage/app/booking_release/launch_readiness',
    'groups' => [
        'environment_runtime' => 'Environment/runtime',
        'api_surface_contract' => 'API surface/contract',
        'booking_core_flows' => 'Booking core flows',
        'performance_resilience' => 'Performance/resilience',
        'disaster_recovery' => 'Disaster recovery',
        'payment_checkout_financial_flows' => 'Payment/checkout financial flows',
        'notifications_alerts' => 'Notifications/alerts',
        'feature_flag_posture' => 'Feature flag posture',
        'release_artifact_integrity' => 'Release artifact integrity',
    ],
    'manual_evidence_max_age_days' => [
        'disaster_recovery_restore_evidence' => 14,
    ],
    'performance_required_surfaces' => [
        'table_board_load',
        'open_walk_in_service_session',
        'add_order_item',
        'kds_board_dispatch',
        'checkout_payment_capture',
        'refund_preview_execute',
        'inventory_stock_read_adjustment',
        'reporting_snapshot_read',
    ],
    'uat_required_scenarios' => [
        'customer_reservation_hold_access_session',
        'staff_auth_branch_scope',
        'walk_in_table_service_session',
        'order_item_lifecycle',
        'kds_dispatch_update',
        'checkout_cashier_shift',
        'refund_cancel_after_payment',
        'inventory_consumption_adjustment',
        'notification_outbox_visibility',
    ],
    'targets' => [
        'staging' => [
            'label' => 'serious-staging',
        ],
        'limited-production' => [
            'label' => 'limited-production',
        ],
    ],
    'matrix' => [
        [
            'key' => 'doctor_environment_runtime',
            'group' => 'environment_runtime',
            'label' => 'Booking doctor baseline',
            'source' => 'booking:doctor',
            'severity' => 'blocking',
            'pass_criteria' => 'Environment validation has no errors and runtime DB/Redis/scheduler/outbox probes all pass.',
            'failure_meaning' => 'The runtime baseline is unsafe for rollout because a hard prerequisite or live dependency is unhealthy.',
            'remediation_hint' => 'Fix the reported environment/runtime failure, confirm scheduler heartbeat freshness, then rerun booking:doctor and booking:launch-readiness.',
        ],
        [
            'key' => 'deploy_preflight_guardrail',
            'group' => 'environment_runtime',
            'label' => 'Deploy preflight guardrail',
            'source' => 'booking:deploy-check --mode=preflight',
            'severity' => 'blocking',
            'pass_criteria' => 'Preflight deploy checks report no blocking errors across environment, migration, data, artifact, or ops guards.',
            'failure_meaning' => 'The build has preflight drift or invariant failures that can break bootstrap, data safety, or operational readiness.',
            'remediation_hint' => 'Resolve the failing deploy-check sections before attempting staging or limited-production rollout.',
        ],
        [
            'key' => 'day1_feature_flag_posture',
            'group' => 'feature_flag_posture',
            'label' => 'Day-1 feature flag posture',
            'source' => 'config/feature_flags.php',
            'severity' => 'blocking',
            'pass_criteria' => 'Every target-required day-1 feature flag is explicitly registered, kill-switchable, and has the expected production-like wildcard default.',
            'failure_meaning' => 'A sensitive feature could be enabled by default for staging or limited production without matching release evidence.',
            'remediation_hint' => 'Restore the configured wildcard default or update the release ticket and readiness config only after the feature is intentionally in launch scope.',
        ],
        [
            'key' => 'route_inventory_contract',
            'group' => 'api_surface_contract',
            'label' => 'Locked route inventory',
            'source' => 'booking:route-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The runtime API surface matches the locked route inventory without action or middleware drift.',
            'failure_meaning' => 'The API surface has drifted from the approved route inventory and may break clients or rollout assumptions.',
            'remediation_hint' => 'Reconcile the route inventory fixture or restore the expected routes before promotion.',
        ],
        [
            'key' => 'openapi_release_contract',
            'group' => 'api_surface_contract',
            'label' => 'Frozen OpenAPI contract artifact',
            'source' => 'booking:release-manifest',
            'severity' => 'blocking',
            'pass_criteria' => 'The release manifest contains a present OpenAPI contract artifact with all required fragments.',
            'failure_meaning' => 'The release bundle is missing the frozen API contract or it has drifted from the required surface.',
            'remediation_hint' => 'Regenerate or repair the OpenAPI release artifact and refresh the release manifest snapshot.',
        ],
        [
            'key' => 'core_ops_flow_gate',
            'group' => 'booking_core_flows',
            'label' => 'Core ops flow suite',
            'source' => 'booking:core-ops-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The canonical core ops suite passes for availability, table holds, reservations, staff floor flows, and waiting-list lifecycle.',
            'failure_meaning' => 'Core booking flows are regressing, so the build is not ready even if route or contract checks stay green.',
            'remediation_hint' => 'Fix the failing core flow tests and rerun the core ops gate before promotion.',
        ],
        [
            'key' => 'round5_financial_gate',
            'group' => 'payment_checkout_financial_flows',
            'label' => 'Round 5 financial suite',
            'source' => 'booking:round5-gate',
            'severity' => 'blocking',
            'pass_criteria' => 'The canonical financial suite passes for checkout, refunds, payment provider/webhook, deposit sessions, and bill self-payment.',
            'failure_meaning' => 'Checkout or payment integrity is regressing, so the build is not safe for staged or limited-production rollout.',
            'remediation_hint' => 'Fix the failing financial tests and rerun the Round 5 gate before promotion.',
        ],
        [
            'key' => 'operational_alert_snapshot',
            'group' => 'notifications_alerts',
            'label' => 'Operational alert snapshot',
            'source' => 'booking:alert-check',
            'severity' => 'blocking',
            'pass_criteria' => 'The operational alert snapshot produces no critical alerts; warning alerts are reviewed explicitly.',
            'failure_meaning' => 'Active operational alerts indicate backlog, payment-integrity, or ops-health conditions that could degrade rollout safety.',
            'remediation_hint' => 'Resolve the underlying alert causes, then rerun the launch readiness gate and confirm the alert snapshot is clean.',
        ],
        [
            'key' => 'release_manifest_snapshot',
            'group' => 'release_artifact_integrity',
            'label' => 'Release manifest snapshot health',
            'source' => 'booking:release-manifest',
            'severity' => 'blocking',
            'pass_criteria' => 'The release manifest snapshot completes without missing required artifacts, missing fragments, or patch inventory failures.',
            'failure_meaning' => 'The release bundle is incomplete or inconsistent, so release evidence cannot be trusted.',
            'remediation_hint' => 'Repair the missing artifact, contract fragment, or SQL patch inventory and rerun booking:release-manifest.',
        ],
        [
            'key' => 'release_manifest_frozen',
            'group' => 'release_artifact_integrity',
            'label' => 'Frozen manifest freshness',
            'source' => 'booking:release-manifest --verify-frozen',
            'severity' => 'blocking',
            'pass_criteria' => 'The live release manifest matches the frozen snapshot used for promotion.',
            'failure_meaning' => 'Release evidence has drifted since the frozen manifest snapshot was captured, so packaging or rollout evidence is stale.',
            'remediation_hint' => 'Refresh the frozen release manifest snapshot after regenerating the intended release evidence.',
        ],
        [
            'key' => 'release_package_integrity',
            'group' => 'release_artifact_integrity',
            'label' => 'Immutable release package build',
            'source' => 'booking:package-release --verify-frozen',
            'severity' => 'blocking',
            'pass_criteria' => 'The immutable package builds successfully with sidecar metadata, inventory, and checksums.',
            'failure_meaning' => 'The candidate build cannot be packaged into the release artifact expected for rollout.',
            'remediation_hint' => 'Fix packaging blockers or frozen-manifest issues, then rebuild the immutable package.',
        ],
    ],
    'day1_feature_flags' => [
        [
            'feature_key' => 'customer.bill_self_payment',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_staff_settlement_only',
            'reason' => 'Customer bill self-payment stays off for day 1. Bill preview and active-order reads may remain contract-visible, but settlement stays staff-owned until real provider evidence promotes customer self-pay.',
        ],
        [
            'feature_key' => 'waiting_list.advanced_automation',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_manual_ops',
            'reason' => 'Customer waiting-list stays off by default and staff waiting-list remains manual on day 1; advanced automation must stay disabled.',
        ],
        [
            'feature_key' => 'staff.kitchen_dispatch',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_not_launch_scope',
            'reason' => 'Kitchen/KDS dispatch and ticket mutations are not part of the day-1 launch promise, even if read-only kitchen routes remain visible.',
        ],
        [
            'feature_key' => 'inventory.uplift',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_not_launch_scope',
            'reason' => 'Advanced inventory and purchasing workflows are not part of the day-1 limited-production scope.',
        ],
        [
            'feature_key' => 'staff.conversation_inbox',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_operator_holdback',
            'reason' => 'Conversation inbox may remain contract-visible, but it is held back from the day-1 operator promise until dedicated evidence promotes it.',
        ],
        [
            'feature_key' => 'staff.conversation_ai_assist',
            'required_for' => ['staging', 'limited-production'],
            'expected_default_enabled' => false,
            'launch_scope' => 'off_day1_optional_assist',
            'reason' => 'AI assist is optional and must not be enabled by default for day-1.',
        ],
    ],
    'manual_checks' => [
        [
            'key' => 'uat_scenario_pack_replay',
            'group' => 'booking_core_flows',
            'label' => 'Canonical UAT scenario pack replay',
            'source' => 'UAT/demo scenario pack',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Run the canonical UAT/demo scenario pack against the candidate build and capture operator evidence.',
            'failure_meaning' => 'Automated suites passed, but operator-level end-to-end confirmation for seeded booking flows is still missing.',
            'remediation_hint' => 'Run the UAT bootstrap/scenario scripts and record the evidence in a manual evidence JSON file.',
            'runbook_path' => 'docs/runbooks/uat-demo-scenario-pack.md',
            'operator_commands' => [
                'pwsh -File .\\scripts\\uat\\Bootstrap-UatPack.ps1 -BaseUrl <base-url>',
                'pwsh -File .\\scripts\\uat\\Invoke-UatScenario.ps1 -Scenario all',
            ],
            'operator_notes' => [
                'Capture the scenario summary and record the result under uat_scenario_pack_replay in the manual evidence JSON.',
                'Do not paste demo passwords, access tokens, staff API keys, or customer tokens into the evidence file.',
            ],
            'evidence_template' => [
                'scenario_pack_version' => '',
                'replayed_at_utc' => '',
                'verification_result' => '',
                'production_artifact_contains_demo_credentials' => false,
                'scenario_results' => [
                    'customer_reservation_hold_access_session' => 'missing',
                    'staff_auth_branch_scope' => 'missing',
                    'walk_in_table_service_session' => 'missing',
                    'order_item_lifecycle' => 'missing',
                    'kds_dispatch_update' => 'missing',
                    'checkout_cashier_shift' => 'missing',
                    'refund_cancel_after_payment' => 'missing',
                    'inventory_consumption_adjustment' => 'missing',
                    'notification_outbox_visibility' => 'missing',
                ],
            ],
            'evidence_schema' => [
                'required_string_fields' => [
                    'scenario_pack_version',
                    'replayed_at_utc',
                    'verification_result',
                ],
                'required_boolean_fields' => [
                    'production_artifact_contains_demo_credentials',
                ],
                'required_scenario_results' => [
                    'customer_reservation_hold_access_session',
                    'staff_auth_branch_scope',
                    'walk_in_table_service_session',
                    'order_item_lifecycle',
                    'kds_dispatch_update',
                    'checkout_cashier_shift',
                    'refund_cancel_after_payment',
                    'inventory_consumption_adjustment',
                    'notification_outbox_visibility',
                ],
            ],
        ],
        [
            'key' => 'disaster_recovery_restore_evidence',
            'group' => 'disaster_recovery',
            'label' => 'Backup restore / disaster recovery evidence',
            'source' => 'booking:dr-drill or operator DR restore record',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Capture recent backup restore evidence from booking:dr-drill full-isolated-restore or an equivalent reviewed manual restore record.',
            'failure_meaning' => 'The candidate lacks recent proof that a backup can be restored and verified without touching the live database.',
            'remediation_hint' => 'Run a dry or full isolated DR rehearsal against a scratch target, archive the report, and record the safe restore evidence fields.',
            'runbook_path' => 'docs/runbooks/booking-disaster-recovery-drill.md',
            'operator_commands' => [
                'php artisan booking:dr-drill --mode=metadata-verify --json',
                'php artisan booking:dr-drill --mode=dry-restore --manifest=<manifest.json> --target-db=<scratch_restore_db> --json',
                'php artisan booking:dr-drill --mode=full-isolated-restore --manifest=<manifest.json> --target-db=<scratch_restore_db> --drop-target-first --json',
            ],
            'operator_notes' => [
                'Use a scratch database name containing restore, rehearsal, drill, sandbox, or tmp.',
                'Do not run destructive restore commands against the application database.',
                'Record the dump identifier, target, verification command/result, operator, and reviewer without secrets.',
            ],
            'evidence_template' => [
                'restored_dump_identifier' => '',
                'restore_target' => '',
                'verification_command' => '',
                'verification_result' => '',
                'operator' => '',
                'reviewer' => '',
            ],
            'evidence_schema' => [
                'required_string_fields' => [
                    'restored_dump_identifier',
                    'restore_target',
                    'verification_command',
                    'verification_result',
                ],
            ],
        ],
        [
            'key' => 'performance_verification_report',
            'group' => 'performance_resilience',
            'label' => 'Performance verification report',
            'source' => 'booking:performance-verify',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Capture the candidate-specific performance verification report, including the automated load scenarios and any required operator-assisted staging probes.',
            'failure_meaning' => 'The rollout target still lacks candidate-specific performance/resilience evidence for read-heavy and contention-sensitive flows.',
            'remediation_hint' => 'Run booking:performance-verify for the candidate build, archive the report, and record it in the manual evidence JSON before limited production.',
            'runbook_path' => 'docs/runbooks/booking-performance-verification.md',
            'operator_commands' => [
                'php artisan booking:performance-verify --profile=staging --run --base-url=<base-url> --manifest-path=storage/app/uat/scenario-pack.json --promote-baseline',
                'php artisan notifications:outbox-health --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'Archive the candidate-specific performance report and record its outcome under performance_verification_report in the manual evidence JSON.',
                'Local smoke timing is useful for regression diagnosis, but limited production requires staging profile evidence.',
            ],
            'evidence_template' => [
                'report_path' => '',
                'profile' => '',
                'evidence_level' => '',
                'verification_result' => '',
                'evaluated_at_utc' => '',
                'local_smoke_only' => true,
                'scenario_matrix' => [
                    'table_board_load' => 'missing',
                    'open_walk_in_service_session' => 'missing',
                    'add_order_item' => 'missing',
                    'kds_board_dispatch' => 'missing',
                    'checkout_payment_capture' => 'missing',
                    'refund_preview_execute' => 'missing',
                    'inventory_stock_read_adjustment' => 'missing',
                    'reporting_snapshot_read' => 'missing',
                ],
            ],
            'evidence_schema' => [
                'required_string_fields' => [
                    'report_path',
                    'profile',
                    'evidence_level',
                    'verification_result',
                    'evaluated_at_utc',
                ],
                'required_boolean_fields' => [
                    'local_smoke_only',
                ],
                'required_surfaces' => [
                    'table_board_load',
                    'open_walk_in_service_session',
                    'add_order_item',
                    'kds_board_dispatch',
                    'checkout_payment_capture',
                    'refund_preview_execute',
                    'inventory_stock_read_adjustment',
                    'reporting_snapshot_read',
                ],
            ],
        ],
        [
            'key' => 'payment_provider_external_e2e',
            'group' => 'payment_checkout_financial_flows',
            'label' => 'Payment provider / customer self-pay readiness',
            'source' => 'Payment provider readiness evidence',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Record whether customer self-pay is intentionally disabled or, if enabled, capture deposit/bill scope, provider mode, webhook, signature, idempotency, failure/cancel, and settlement reconciliation evidence.',
            'failure_meaning' => 'The release either enables customer self-pay without provider proof or lacks an explicit staff-settlement-only payment readiness record.',
            'remediation_hint' => 'Keep customer self-pay disabled for day 1 or attach schema-valid provider readiness evidence before limited production.',
            'runbook_path' => 'docs/runbooks/booking-launch-readiness.md',
            'operator_commands' => [
                'php artisan booking:round5-gate --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'When customer self-pay is disabled, confirm staff settlement remains the day-1 payment path.',
                'When customer self-pay is enabled, use sandbox/live provider evidence and never paste provider secrets or credentials into the evidence JSON.',
            ],
            'evidence_template' => [
                'customer_self_pay_enabled' => false,
                'staff_settlement_day1_path_confirmed' => false,
                'provider_code' => '',
                'provider_mode' => '',
                'scopes' => [
                    'deposit' => 'missing',
                    'bill' => 'missing',
                ],
                'callback_webhook_tested' => false,
                'signature_validation_tested' => false,
                'idempotency_replay_tested' => false,
                'failure_cancel_path_tested' => false,
                'settlement_reconciliation_tested' => false,
            ],
            'evidence_schema' => [
                'required_string_fields' => [
                    'provider_mode',
                ],
                'required_boolean_fields' => [
                    'customer_self_pay_enabled',
                ],
            ],
        ],
        [
            'key' => 'notification_provider_external_e2e',
            'group' => 'notifications_alerts',
            'label' => 'Real notification delivery rehearsal',
            'source' => 'Notification outbox / provider manual rehearsal',
            'required_for' => ['limited-production'],
            'recommended_for' => ['staging'],
            'pass_criteria' => 'Validate one end-to-end external notification delivery path against the target mailer/provider and capture both outbox attempt evidence and recipient confirmation.',
            'failure_meaning' => 'Outbox health and retry logic passed, but the rollout target still lacks proof that a real external notification reached the intended recipient.',
            'remediation_hint' => 'Run a staging notification delivery rehearsal against the real email provider and capture the evidence before limited production.',
            'runbook_path' => 'docs/runbooks/notification-platform-v2.md',
            'operator_commands' => [
                'php artisan notifications:outbox-health --json',
                'php artisan booking:alert-check --json',
            ],
            'operator_notes' => [
                'Trigger one real Email notification against the target mailer/provider, confirm notification_outbox and notification_delivery_attempts, then record the recipient confirmation under notification_provider_external_e2e.',
            ],
        ],
        [
            'key' => 'concurrency_rehearsal',
            'group' => 'booking_core_flows',
            'label' => 'Multi-process concurrency rehearsal',
            'source' => 'Staging concurrency drill',
            'required_for' => ['limited-production'],
            'recommended_for' => [],
            'pass_criteria' => 'Run a Redis/MySQL-backed multi-process rehearsal for table hold and checkout concurrency on staging.',
            'failure_meaning' => 'Single-process automated tests passed, but rollout-level race protection has not been exercised under realistic contention.',
            'remediation_hint' => 'Execute the staging concurrency drill and store the result as manual evidence before limited production.',
            'runbook_path' => 'docs/runbooks/booking-performance-verification.md',
            'operator_commands' => [
                'php artisan booking:performance-verify --profile=staging --run --base-url=<base-url> --scenario=reservation_create_race --scenario=checkout_preview_load',
            ],
            'operator_notes' => [
                'Run the probe while Redis/MySQL contention is injected on staging, archive the report, then record the result under concurrency_rehearsal.',
            ],
        ],
    ],
    'automation_gaps' => [
        [
            'key' => 'uat_pack_operator_evidence',
            'group' => 'booking_core_flows',
            'severity' => 'info',
            'description' => 'The project has a canonical UAT/demo scenario pack, but launch readiness does not auto-run or auto-assert every scenario yet.',
            'recommended_evidence' => 'Store operator evidence from the UAT scenario pack in the manual evidence JSON file.',
        ],
        [
            'key' => 'real_payment_provider_callback',
            'group' => 'payment_checkout_financial_flows',
            'severity' => 'info',
            'description' => 'Round 5 gate validates internal payment flows and adapters, but provider readiness still requires explicit self-pay disabled or sandbox/live provider evidence.',
            'recommended_evidence' => 'Record payment_provider_external_e2e evidence before limited production.',
        ],
        [
            'key' => 'backup_restore_recoverability',
            'group' => 'disaster_recovery',
            'severity' => 'info',
            'description' => 'Automated tests do not run destructive restore commands; limited production requires recent DR drill or safe manual restore evidence.',
            'recommended_evidence' => 'Record disaster_recovery_restore_evidence from booking:dr-drill or a reviewed scratch-target restore.',
        ],
        [
            'key' => 'performance_verification_candidate_report',
            'group' => 'performance_resilience',
            'severity' => 'info',
            'description' => 'Local query-budget tests help catch regressions, but they do not replace a candidate-specific booking:performance-verify report with staging probes and resilience evidence.',
            'recommended_evidence' => 'Archive one candidate-specific performance verification report before limited production.',
        ],
        [
            'key' => 'real_notification_delivery',
            'group' => 'notifications_alerts',
            'severity' => 'info',
            'description' => 'Outbox tests and health checks validate enqueue, retry, and alerting, but they do not prove that the real target mailer/provider delivered a live notification.',
            'recommended_evidence' => 'Record one staging notification delivery rehearsal before limited production.',
        ],
        [
            'key' => 'multi_process_contention',
            'group' => 'booking_core_flows',
            'severity' => 'info',
            'description' => 'The automated gates do not simulate multi-process Redis/MySQL contention at rollout load.',
            'recommended_evidence' => 'Attach the result of a staging concurrency rehearsal before limited production.',
        ],
    ],
    'credentials' => [
        'DB_PASSWORD' => env('DB_PASSWORD'),
        'REDIS_HOST' => env('REDIS_HOST'),
        'AWS_ACCESS_KEY_ID' => env('AWS_ACCESS_KEY_ID'),
        'BACKUP_S3_BUCKET' => env('BACKUP_S3_BUCKET'),
        'MAIL_USERNAME' => env('MAIL_USERNAME'),
        'MAIL_PASSWORD' => env('MAIL_PASSWORD'),
        'SENTRY_LARAVEL_DSN' => env('SENTRY_LARAVEL_DSN'),
        'OPS_ALERTS_WEBHOOK_URL' => env('OPS_ALERTS_WEBHOOK_URL'),
        'VNPAY_TMN_CODE' => env('VNPAY_TMN_CODE'),
        'MOMO_PARTNER_CODE' => env('MOMO_PARTNER_CODE'),
        'STAGING_BASE_URL' => env('STAGING_BASE_URL'),
    ],
];
