<?php

declare(strict_types=1);

$canonicalReleaseContractFragments = [
    'is_preorder_enabled',
    'preorder_quota_per_day',
    'preorder_cutoff_minutes',
    'idx_user_vouchers__voucher_id__is_used__user_id',
    'idx_table_holds__session_id__confirmed_reservation_id',
    'chk_reservations__deposit_status',
    'chk_waiting_list__status_notified_requires_window',
    'chk_waiting_list__status_seated_requires_timestamp',
    'chk_waiting_list__status_cancelled_requires_timestamp',
    'uq_agent_assignments__active_conversation_id',
    'uq_bank_accounts__default_user_id',
    'chk_reservations__money_nonneg',
    'chk_reservations__reserved_requires_checked_in_at',
    'active_applied_user_voucher_id',
    'uq_reservations__active_applied_user_voucher_id',
    'uq_payments__payment_provider__transaction_code',
    'chk_table_holds__time_range',
    "`channel` enum('SMS','Email','Zalo','Push','Webhook')",
    '`role_id` int unsigned NOT NULL,',
    'CREATE TABLE `staff_api_keys` (',
    'uq_staff_api_keys__key_hash',
    'chk_staff_api_keys__label_nonempty',
    'CREATE PROCEDURE `sp_cleanup_expired_holds`()',
    'CURRENT_TIMESTAMP(6)',
    '`recipient_user_id` int unsigned DEFAULT NULL,',
    '`dedupe_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,',
    'CREATE TABLE `notification_delivery_attempts` (',
    'CREATE TABLE `notification_preferences` (',
    'uq_notification_preferences__user_id__channel',
    'chk_notification_preferences__quiet_window',
    '`actor_type` varchar(40) DEFAULT NULL,',
    '`summary_json` json DEFAULT NULL,',
    '`request_id` varchar(64) DEFAULT NULL,',
    'CREATE TABLE `audit_log_subjects` (',
    'idx_audit_log_subjects__subject_type__subject_id__audit_id',
    '`business_hours` json DEFAULT NULL,',
    '`closure_windows` json DEFAULT NULL,',
    '`booking_policy` json DEFAULT NULL,',
    'CREATE TABLE `customer_privacy_requests` (',
    '`privacy_anonymized_at` datetime(6) DEFAULT NULL,',
    'CREATE TABLE `feature_flags` (',
    'CREATE TABLE `finance_replay_records` (',
    'uq_finance_replay_records__scope_aggregate_key',
    'fk_reservations__branch_id__branches',
    'fk_table_holds__branch_id__branches',
    'fk_cashier_shifts__branch_id__branches',
    'fk_cashier_shifts__cashier_user_id__users',
    'fk_cashier_shifts__opened_by__users',
    'fk_cashier_shifts__closed_by__users',
    'trg_cashier_shifts__bi_row_version',
    'trg_cashier_shifts__bu_row_version',
    'trg_ingredients__bi_row_version',
    'trg_ingredients__bu_row_version',
    'trg_menu_item_recipes__bi_row_version',
    'trg_menu_item_recipes__bu_row_version',
    'trg_suppliers__bi_row_version',
    'trg_suppliers__bu_row_version',
    'trg_purchase_orders__bi_row_version',
    'trg_purchase_orders__bu_row_version',
    'chk_reservation_order_items__line_total_matches',
    'CREATE TABLE `staff_branch_assignments` (',
    'uq_staff_branch_assignments__user_id__branch_id',
    'fk_staff_branch_assignments__user_id__users',
    'fk_staff_branch_assignments__branch_id__branches',
];

return [
    'artifacts' => [
        'schema_dump' => [
            'path' => 'database/schema/mysql-schema.sql',
            'optional' => false,
            'required_fragments' => $canonicalReleaseContractFragments,
        ],
        'full_dump' => [
            'path' => 'db_all.sql',
            'optional' => false,
            'required_fragments' => $canonicalReleaseContractFragments,
        ],
        'release_contract_verifier' => [
            'path' => 'tools/mysql/verify_release_contract.sql',
            'optional' => false,
            'required_fragments' => [
                'reservations.completed_paid_bill_snapshot:ok',
                '__drifted_completed_paid_reservations_missing_bill_snapshot__',
            ],
        ],
        'core_ops_gate_definition' => [
            'path' => 'tests/fixtures/core_ops_gate_suite.json',
            'optional' => false,
            'required_fragments' => [
                '"suite": "core_ops"',
                '"tests"',
                'tests/Feature/Table/TableHoldHttpFlowTest.php',
            ],
        ],
        'round5_gate_definition' => [
            'path' => 'tests/fixtures/round5_gate_suite.json',
            'optional' => false,
            'required_fragments' => [
                '"suite": "round5"',
                '"tests"',
                'tests/Feature/Staff/StaffCheckoutFinancialOutboxAndCoverageTest.php',
            ],
        ],
        'route_inventory_gate_definition' => [
            'path' => 'tests/fixtures/route_inventory_gate.json',
            'optional' => false,
            'required_fragments' => [
                '"suite": "route_inventory"',
                '"expected_routes"',
                '"smoke_requests"',
            ],
        ],
        'openapi_v1_spec' => [
            'path' => 'storage/app/booking_release/openapi-v1.json',
            'optional' => false,
            'required_fragments' => [
                '"openapi": "3.1.0"',
                '"title": "RestaurantPOS API Contract"',
                '"/api/v1/auth/customer/login"',
                '"/api/v1/payments/providers/{provider_code}/webhooks"',
                '"/api/v1/staff/orders/{order_id}/settlement/finalize"',
            ],
        ],
        'api_consumer_collection' => [
            'path' => 'build/api-consumer/postman/RestaurantPOS.postman_collection.json',
            'optional' => false,
            'required_fragments' => [
                '"name": "RestaurantPOS API Consumer Collection"',
                '/api/v1/auth/customer/login',
                '/api/v1/payments/providers/{{providerCode}}/webhooks',
            ],
        ],
        'api_consumer_local_environment' => [
            'path' => 'build/api-consumer/postman/RestaurantPOS.local.template.postman_environment.json',
            'optional' => false,
            'required_fragments' => [
                '"name": "RestaurantPOS Local"',
                '"key": "baseUrl"',
                '"key": "staffApiKey"',
            ],
        ],
        'api_consumer_staging_environment' => [
            'path' => 'build/api-consumer/postman/RestaurantPOS.staging.template.postman_environment.json',
            'optional' => false,
            'required_fragments' => [
                '"name": "RestaurantPOS Staging"',
                '"key": "baseUrl"',
                '"key": "staffApiKey"',
            ],
        ],
        'api_consumer_sdk_typescript' => [
            'path' => 'build/api-consumer/sdk/typescript/restaurantpos-sdk.ts',
            'optional' => false,
            'required_fragments' => [
                'export class RestaurantPosClient',
                'postV1AuthCustomerLogin',
                'RestaurantPosApiError',
            ],
        ],
        'api_consumer_sdk_enums_typescript' => [
            'path' => 'build/api-consumer/sdk/typescript/restaurantpos-enums.ts',
            'optional' => false,
            'required_fragments' => [
                'export const reservationStatusValues',
                'export type ReservationStatus',
                'semanticAliases',
            ],
        ],
        'api_consumer_sdk_readme' => [
            'path' => 'build/api-consumer/sdk/typescript/README.md',
            'optional' => false,
            'required_fragments' => [
                '# RestaurantPOS TypeScript SDK Foundation',
                'booking:api-artifacts:generate',
                'Generated from',
            ],
        ],
        'api_consumer_enum_state_json' => [
            'path' => 'build/api-consumer/enum-state-map.json',
            'optional' => false,
            'required_fragments' => [
                '"enums"',
                '"ReservationStatus"',
                '"semantic_aliases"',
            ],
        ],
        'api_consumer_mutation_contract' => [
            'path' => 'build/api-consumer/mutation-contracts.md',
            'optional' => false,
            'required_fragments' => [
                '# RestaurantPOS Mutation Contract Matrix',
                'Idempotency-Key',
                'X-Session-Id',
                'PATCH api/v1/admin/settings/branches/{id}',
            ],
        ],
        'core_ops_gate_snapshot' => [
            'path' => 'storage/app/booking_release/core_ops_gate_snapshot.json',
            'optional' => false,
            'required_fragments' => [
                '"suite": "core_ops"',
                '"definition_path": "tests/fixtures/core_ops_gate_suite.json"',
                '"snapshot_path": "storage/app/booking_release/core_ops_gate_snapshot.json"',
                'tests/Feature/Table/TableHoldHttpFlowTest.php',
                '"summary"',
                '"tests"',
            ],
        ],
        'round5_gate_snapshot' => [
            'path' => 'storage/app/booking_release/round5_gate_snapshot.json',
            'optional' => false,
            'required_fragments' => [
                '"suite": "round5"',
                '"definition_path": "tests/fixtures/round5_gate_suite.json"',
                '"snapshot_path": "storage/app/booking_release/round5_gate_snapshot.json"',
                'tests/Feature/Staff/StaffCheckoutFinancialOutboxAndCoverageTest.php',
                '"summary"',
                '"tests"',
            ],
        ],
        'release_manifest_snapshot' => [
            'path' => 'storage/app/booking_release/release_manifest_snapshot.json',
            'optional' => false,
            'required_fragments' => [
                '"definition_path": "config/booking_release.php"',
                '"snapshot_path": "storage/app/booking_release/release_manifest_snapshot.json"',
                '"artifacts"',
            ],
        ],
    ],
    'artifact_freshness' => [
        'api_consumer_collection' => ['openapi_v1_spec'],
        'api_consumer_local_environment' => ['openapi_v1_spec'],
        'api_consumer_staging_environment' => ['openapi_v1_spec'],
        'api_consumer_sdk_typescript' => ['openapi_v1_spec'],
        'api_consumer_sdk_enums_typescript' => ['openapi_v1_spec'],
        'api_consumer_sdk_readme' => ['openapi_v1_spec'],
        'api_consumer_enum_state_json' => ['openapi_v1_spec'],
        'api_consumer_mutation_contract' => ['openapi_v1_spec'],
    ],
    'required_sql_patches' => [
        '2026_03_14_000015_access_contract_and_portability_hardening.sql',
        '2026_03_15_000016_financial_invariants_hardening.sql',
        '2026_03_15_000017_payment_refund_lineage_guard.sql',
        '2026_03_15_000018_voucher_and_session_access_indexes.sql',
        '2026_03_15_000019_top_priority_release_alignment.sql',
        '2026_03_15_000020_contract_integrity_and_portability_round.sql',
        '2026_03_15_000021_release_consistency_and_waiting_list_hardening.sql',
        '2026_03_15_000022_staff_auth_and_integrity_hardening.sql',
        '2026_03_15_000022_staff_auth_and_integrity_hardening_hotfix.sql',
        '2026_03_15_000023_menu_price_and_active_voucher_integrity.sql',
        '2026_03_15_000024_payment_reconciliation_and_table_audit_round.sql',
        '2026_03_15_000025_staff_api_key_lifecycle_round.sql',
        '2026_03_16_000023_contract_cleanup_and_reference_data.sql',
        '2026_03_16_000023_financial_contract_and_role_hardening.sql',
        '2026_03_21_000026_customer_waiting_list_notified_response_flow.sql',
        '2026_03_21_000027_customer_reservation_deposit_self_service_intent.sql',
        '2026_03_21_000028_customer_deposit_payment_sessions.sql',
        '2026_03_21_000029_customer_bill_payment_sessions.sql',
        '2026_03_22_000030_payment_provider_webhook_receipts.sql',
        '2026_03_25_000031_customer_access_sessions_foundation.sql',
        '2026_03_25_000032_customer_waiting_list_guest_session_linkage.sql',
        '2026_03_25_000033_waiting_list_customer_session_access.sql',
        '2026_03_27_000034_cashier_shifts_foundation.sql',
        '2026_03_27_000035_inventory_recipe_stock_foundation.sql',
        '2026_03_28_000036_kitchen_routing_foundation.sql',
        '2026_03_28_000037_purchasing_supplier_receiving_foundation.sql',
        '2026_03_28_000038_tax_invoice_accounting_export_foundation.sql',
        '2026_03_28_000039_multi_branch_foundation.sql',
        '2026_03_28_000040_reporting_read_models_analytics_foundation.sql',
        '2026_04_01_000041_waiting_list_db_contract_reconciliation.sql',
        '2026_04_04_000042_waiting_list_active_owner_invariant.sql',
        '2026_04_04_000043_waiting_list_user_fk_generated_column_hotfix.sql',
        '2026_04_05_000044_staff_conversation_inbox_foundation.sql',
        '2026_04_05_000045_notification_platform_v2_foundation.sql',
        '2026_04_05_000046_unified_audit_trail_foundation.sql',
        '2026_04_05_000047_branch_scheduling_policy_foundation.sql',
        '2026_04_05_000047_data_lifecycle_foundation.sql',
        '2026_04_05_000048_feature_flags_foundation.sql',
        '2026_04_08_000041_drop_runtime_incompatible_payment_refund_triggers.sql',
        '2026_04_11_000049_reservation_guest_snapshot_support.sql',
        '2026_04_12_000050_staff_conversation_workflow_hardening.sql',
        '2026_04_13_000051_inventory_stock_movement_reference_uniqueness.sql',
        '2026_04_15_000052_finance_replay_records.sql',
        '2026_04_20_000053_confirmed_hold_conflict_scope_alignment.sql',
        '2026_04_24_000054_branch_fk_integrity_guard.sql',
        '2026_04_24_000055_staff_branch_assignments_foundation.sql',
        '2026_04_24_000056_kitchen_branch_routing_scope.sql',
        '2026_04_25_000057_kitchen_ticket_row_version.sql',
        '2026_04_26_000058_cashier_shift_user_fk_contract.sql',
        '2026_04_27_000059_cashier_shift_row_version.sql',
        '2026_04_27_000060_order_item_line_total_invariant.sql',
        '2026_04_28_000061_inventory_master_data_row_version.sql',
        '2026_04_29_000062_payment_cashier_shift_link.sql',
        '2026_04_29_000063_completed_paid_bill_snapshot_gate.sql',
        '2026_05_14_000064_moc_sen_story_data_pack.sql',
        '2026_06_02_000065_canonical_roles_data.sql',
        '2026_06_14_000066_menu_combo_and_favorites.sql',
        '2026_06_20_000067_professional_menu_rebuild.sql',
        '2026_06_21_000068_update_menu_vietnamese_accents.sql',
        '2026_07_19_000071_order_item_recipe_snapshot.sql',
    ],
    'release_manifest' => [
        'definition_path' => 'config/booking_release.php',
        'snapshot_path' => 'storage/app/booking_release/release_manifest_snapshot.json',
    ],
    'core_ops_gate' => [
        'definition_path' => 'tests/fixtures/core_ops_gate_suite.json',
        'snapshot_path' => 'storage/app/booking_release/core_ops_gate_snapshot.json',
    ],
    'round5_gate' => [
        'definition_path' => 'tests/fixtures/round5_gate_suite.json',
        'snapshot_path' => 'storage/app/booking_release/round5_gate_snapshot.json',
    ],
    'route_inventory_gate' => [
        'definition_path' => 'tests/fixtures/route_inventory_gate.json',
        'public_controller_prefixes' => ['Customer'],
        'public_controller_exact' => ['PaymentProviderWebhookController'],
        'public_controller_exclusions' => [],
    ],
    'api_contract' => [
        'openapi_path' => 'storage/app/booking_release/openapi-v1.json',
    ],
    'build_metadata' => [
        'commit_sha' => env('APP_RELEASE_SHA') ?: env('GITHUB_SHA') ?: env('CI_COMMIT_SHA'),
        'ref_name' => env('APP_RELEASE_REF') ?: env('GITHUB_REF_NAME') ?: env('CI_COMMIT_REF_NAME'),
        'run_id' => env('GITHUB_RUN_ID') ?: env('CI_PIPELINE_ID'),
    ],
    'release_loop' => [
        'artifact_root' => 'storage/app/booking_release/release_loop',
        'step_timeout_seconds' => 600,
        'preview_timeout_seconds' => 300,
        'preview_link_paths' => [
            '.vercel/project.json',
            'customer-web/.vercel/project.json',
            'staff-web/.vercel/project.json',
        ],
        'observability' => [
            'provider' => 'sentry',
            'required_env' => [
                'SENTRY_AUTH_TOKEN',
                'SENTRY_ORG',
                'SENTRY_PROJECT',
            ],
            'release_env' => [
                'SENTRY_RELEASE',
                'APP_RELEASE_SHA',
                'GITHUB_SHA',
                'CI_COMMIT_SHA',
            ],
            'environment_env' => [
                'SENTRY_ENVIRONMENT',
                'APP_ENV',
            ],
        ],
    ],
    'packaging' => [
        'output_root' => 'build/booking-release',
        'package_prefix' => 'restaurantpos-backend-release',
        'retained_package_sets' => 2,
        'exclude_paths' => [
            'customer-web/node_modules',
            'customer-web/.next',
            'customer-web/out',
            'customer-web/build',
            'customer-web/coverage',
            'customer-web/test-results',
            'customer-web/playwright-report',
            'staff-web/node_modules',
            'staff-web/dist',
            'staff-web/.vite',
        ],
        'include_paths' => [
            ['path' => 'artisan', 'required' => true],
            ['path' => 'composer.json', 'required' => true],
            ['path' => '.env.example', 'required' => true],
            ['path' => 'app', 'required' => true],
            ['path' => 'bootstrap', 'required' => true],
            ['path' => 'build/api-consumer', 'required' => true],
            ['path' => 'config', 'required' => true],
            ['path' => 'database', 'required' => true],
            ['path' => 'package.json', 'required' => true],
            ['path' => 'phpunit.xml', 'required' => true],
            ['path' => 'public/index.php', 'required' => true],
            ['path' => 'routes', 'required' => true],
            ['path' => 'scripts', 'required' => true],
            ['path' => 'customer-web', 'required' => true],
            ['path' => 'staff-web', 'required' => true],
            ['path' => 'storage/app/booking_release', 'required' => true],
            ['path' => 'tests', 'required' => true],
            ['path' => 'tools/bootstrap_booking.php', 'required' => true],
            ['path' => 'docs/runbooks', 'required' => false],
            ['path' => 'README.md', 'required' => false],
            ['path' => 'tools/mysql', 'required' => true],
            ['path' => 'vite.config.js', 'required' => true],
            ['path' => 'db_all.sql', 'required' => true],
        ],
        'sidecars' => [
            'metadata_suffix' => '.metadata.json',
            'inventory_suffix' => '.inventory.json',
            'checksums_suffix' => '.checksums.sha256',
            'package_sha256_suffix' => '.package.sha256',
            'latest_pointer_path' => 'build/booking-release/latest-package.json',
        ],
    ],
];
