<?php

declare(strict_types=1);

return [
    'enforce_known_capabilities' => (bool) env('STAFF_CAPABILITIES_ENFORCE_KNOWN', false),

    'known_capabilities' => [
        'audit.view',
        'cashier.shift.manage',
        'conversation.manage',
        'inventory.manage',
        'kitchen.manage',
        'loyalty.adjust',
        'loyalty.redeem',
        'loyalty.view',
        'menu.manage',
        'ops.health.view',
        'ops.metrics.view',
        'ops.release.view',
        'ops.view',
        'order.manage',
        'payment.refund',
        'privacy.manage',
        'reporting.view',
        'reservation.manage',
        'settings.manage',
        'settlement.manage',
        'table.board.view',
        'table.release',
        'voucher.manage',
        'voucher.master_data.manage',
        'waiting_list.manage',
    ],

    'role_id_capabilities' => [
    ],

    'role_capabilities' => [
        'Admin' => [
            '*',
        ],
        'Staff' => [
            'audit.view',
            'cashier.shift.manage',
            'conversation.manage',
            'table.board.view',
            'reservation.manage',
            'order.manage',
            'kitchen.manage',
            'settlement.manage',
            'payment.refund',
            'reporting.view',
            'voucher.manage',
            'loyalty.view',
            'loyalty.redeem',
            'waiting_list.manage',
            'table.release',
        ],
    ],

    // Compatibility-first branch entitlement until staff-to-branch assignments land.
    // Branch authorization must remain explicit and must not expand from cashier shifts.
    'fallback_branch_scopes' => [
        'default',
    ],

    'role_id_branch_scopes' => [
    ],

    'role_branch_scopes' => [
        'Admin' => [
            '*',
        ],
        'Staff' => [
            'default',
        ],
    ],

    'route_capabilities' => [
        'DELETE api/v1/admin/restaurant/tables/{id}' => 'settings.manage',
        'DELETE api/v1/staff/conversations/{conversation_id}/links/reservation' => 'conversation.manage',
        'DELETE api/v1/staff/conversations/{conversation_id}/links/waiting-list' => 'conversation.manage',
        'GET api/v1/admin/benefits/loyalty-tiers' => 'voucher.master_data.manage',
        'GET api/v1/admin/benefits/loyalty-tiers/export' => 'voucher.master_data.manage',
        'GET api/v1/admin/benefits/loyalty-tiers/{id}' => 'voucher.master_data.manage',
        'GET api/v1/admin/benefits/vouchers' => 'voucher.master_data.manage',
        'GET api/v1/admin/benefits/vouchers/export' => 'voucher.master_data.manage',
        'GET api/v1/admin/benefits/vouchers/{id}' => 'voucher.master_data.manage',
        'GET api/v1/admin/inventory/ingredients' => 'inventory.manage',
        'GET api/v1/admin/inventory/ingredients/{id}' => 'inventory.manage',
        'GET api/v1/admin/inventory/ingredients/{id}/movements' => 'inventory.manage',
        'GET api/v1/admin/inventory/menu-items/{id}/recipe' => 'inventory.manage',
        'GET api/v1/admin/inventory/purchase-orders' => 'inventory.manage',
        'GET api/v1/admin/inventory/purchase-orders/{id}' => 'inventory.manage',
        'GET api/v1/admin/inventory/purchase-orders/{id}/receipts' => 'inventory.manage',
        'GET api/v1/admin/inventory/suppliers' => 'inventory.manage',
        'GET api/v1/admin/inventory/suppliers/{id}' => 'inventory.manage',
        'GET api/v1/admin/kitchen/stations' => 'settings.manage',
        'GET api/v1/admin/kitchen/stations/{station_id}' => 'settings.manage',
        'GET api/v1/admin/kitchen/stations/{station_id}/category-routes' => 'settings.manage',
        'GET api/v1/admin/menu/categories' => 'menu.manage',
        'GET api/v1/admin/menu/categories/export' => 'menu.manage',
        'GET api/v1/admin/menu/items' => 'menu.manage',
        'GET api/v1/admin/menu/items/export' => 'menu.manage',
        'GET api/v1/admin/menu/items/{item_id}' => 'menu.manage',
        'GET api/v1/admin/menu/items/{item_id}/prices' => 'menu.manage',
        'GET api/v1/admin/menu/prices/export' => 'menu.manage',
        'GET api/v1/admin/menu/prices/{price_id}' => 'menu.manage',
        'GET api/v1/admin/privacy/customers/{user_id}/data-export' => 'privacy.manage',
        'GET api/v1/admin/privacy/requests' => 'privacy.manage',
        'GET api/v1/admin/restaurant/table-templates' => 'settings.manage',
        'GET api/v1/admin/restaurant/tables' => 'settings.manage',
        'GET api/v1/admin/restaurant/tables/export' => 'settings.manage',
        'GET api/v1/admin/restaurant/tables/{id}' => 'settings.manage',
        'GET api/v1/admin/restaurant/zones' => 'settings.manage',
        'GET api/v1/admin/settings/benefits' => 'voucher.master_data.manage',
        'GET api/v1/admin/settings/branches' => 'settings.manage',
        'GET api/v1/admin/settings/branches/export' => 'settings.manage',
        'GET api/v1/admin/settings/branches/{id}' => 'settings.manage',
        'GET api/v1/admin/settings/finance/tax-profile' => 'settings.manage',
        'GET api/v1/health/detailed' => 'ops.health.view',
        'GET api/v1/health/redis' => 'ops.health.view',
        'GET api/v1/metrics' => 'ops.metrics.view',
        'GET api/v1/staff/audit-trail' => 'audit.view',
        'GET api/v1/staff/branches' => 'reservation.manage',
        'GET api/v1/staff/cashier/shifts' => 'cashier.shift.manage',
        'GET api/v1/staff/cashier/shifts/current' => 'cashier.shift.manage',
        'GET api/v1/staff/cashier/shifts/{shift_id}' => 'cashier.shift.manage',
        'GET api/v1/staff/conversations' => 'conversation.manage',
        'GET api/v1/staff/conversations/{conversation_id}' => 'conversation.manage',
        'GET api/v1/staff/conversations/{conversation_id}/files/{file_id}/access' => 'conversation.manage',
        'GET api/v1/staff/conversations/{conversation_id}/messages/{message_id}/attachment' => 'conversation.manage',
        'GET api/v1/staff/finance/accounting-export' => 'settlement.manage',
        'GET api/v1/staff/finance/invoices/{reservation_id}' => 'settlement.manage',
        'GET api/v1/staff/finance/reconciliation' => 'settlement.manage',
        'GET api/v1/staff/finance/reconciliation/export' => 'settlement.manage',
        'GET api/v1/staff/finance/reconciliation/{reservation_id}' => 'settlement.manage',
        'GET api/v1/staff/kitchen/changes' => 'kitchen.manage',
        'GET api/v1/staff/kitchen/stations' => 'kitchen.manage',
        'GET api/v1/staff/kitchen/stations/{station_id}/tickets' => 'kitchen.manage',
        'GET api/v1/staff/menu/items' => 'order.manage',
        'GET api/v1/staff/orders/{order_id}' => 'order.manage',
        'GET api/v1/staff/orders/{order_id}/settlement-preview' => 'settlement.manage',
        'GET api/v1/staff/reporting/daily-inventory' => 'reporting.view',
        'GET api/v1/staff/reporting/daily-operations' => 'reporting.view',
        'GET api/v1/staff/reporting/daily-sales' => 'reporting.view',
        'GET api/v1/staff/reservations' => 'reservation.manage',
        'GET api/v1/staff/reservations/timeline' => 'reservation.manage',
        'GET api/v1/staff/reservations/{reservation_id}' => 'reservation.manage',
        'GET api/v1/staff/reservations/{reservation_id}/active-order' => 'order.manage',
        'GET api/v1/staff/reservations/{reservation_id}/deposit-preview' => 'settlement.manage',
        'GET api/v1/staff/reservations/{reservation_id}/loyalty' => 'loyalty.view',
        'GET api/v1/staff/reservations/{reservation_id}/orders' => 'order.manage',
        'GET api/v1/staff/reservations/{reservation_id}/refund-preview' => 'payment.refund',
        'GET api/v1/staff/reservations/{reservation_id}/vouchers' => 'voucher.manage',
        'GET api/v1/staff/table-board' => 'table.board.view',
        'GET api/v1/staff/tables/board' => 'table.board.view',
        'GET api/v1/staff/tables/board/changes' => 'table.board.view',
        'GET api/v1/staff/tables/{table_id}/active-order' => 'order.manage',
        'GET api/v1/staff/tables/{table_id}/active-service-session' => 'reservation.manage',
        'GET api/v1/staff/users/{user_id}/loyalty' => 'loyalty.view',
        'GET api/v1/staff/waiting-list' => 'waiting_list.manage',
        'GET api/v1/staff/waiting-list/changes' => 'waiting_list.manage',
        'PATCH api/v1/admin/benefits/loyalty-tiers/{id}' => 'voucher.master_data.manage',
        'PATCH api/v1/admin/benefits/vouchers/{id}' => 'voucher.master_data.manage',
        'PATCH api/v1/admin/inventory/ingredients/{id}' => 'inventory.manage',
        'PATCH api/v1/admin/inventory/purchase-orders/{id}' => 'inventory.manage',
        'PATCH api/v1/admin/inventory/suppliers/{id}' => 'inventory.manage',
        'PATCH api/v1/admin/kitchen/stations/{station_id}' => 'settings.manage',
        'PATCH api/v1/admin/menu/categories/{category_id}' => 'menu.manage',
        'PATCH api/v1/admin/menu/items/{item_id}' => 'menu.manage',
        'PATCH api/v1/admin/restaurant/tables/{id}' => 'settings.manage',
        'PATCH api/v1/admin/settings/branches/{id}' => 'settings.manage',
        'PATCH api/v1/reservations/{id}/status' => 'reservation.manage',
        'PATCH api/v1/staff/orders/{order_id}/items/{order_item_id}' => 'order.manage',
        'POST api/v1/admin/benefits/loyalty-tiers' => 'voucher.master_data.manage',
        'POST api/v1/admin/benefits/loyalty-tiers/import' => 'voucher.master_data.manage',
        'POST api/v1/admin/benefits/vouchers' => 'voucher.master_data.manage',
        'POST api/v1/admin/benefits/vouchers/import' => 'voucher.master_data.manage',
        'POST api/v1/admin/inventory/ingredients' => 'inventory.manage',
        'POST api/v1/admin/inventory/ingredients/{id}/movements' => 'inventory.manage',
        'POST api/v1/admin/inventory/purchase-orders' => 'inventory.manage',
        'POST api/v1/admin/inventory/purchase-orders/{id}/receipts' => 'inventory.manage',
        'POST api/v1/admin/inventory/suppliers' => 'inventory.manage',
        'POST api/v1/admin/kitchen/stations' => 'settings.manage',
        'POST api/v1/admin/menu/categories' => 'menu.manage',
        'POST api/v1/admin/menu/categories/import' => 'menu.manage',
        'POST api/v1/admin/menu/items' => 'menu.manage',
        'POST api/v1/admin/menu/items/import' => 'menu.manage',
        'POST api/v1/admin/menu/items/{item_id}/prices' => 'menu.manage',
        'POST api/v1/admin/menu/prices/import' => 'menu.manage',
        'POST api/v1/admin/privacy/requests/{request_id}/review' => 'privacy.manage',
        'POST api/v1/admin/restaurant/tables' => 'settings.manage',
        'POST api/v1/admin/restaurant/tables/import' => 'settings.manage',
        'POST api/v1/admin/restaurant/zones/rename' => 'settings.manage',
        'POST api/v1/admin/settings/benefits' => 'voucher.master_data.manage',
        'POST api/v1/admin/settings/branches' => 'settings.manage',
        'POST api/v1/admin/settings/branches/import' => 'settings.manage',
        'POST api/v1/admin/settings/finance/tax-profile' => 'settings.manage',
        'POST api/v1/admin/settings/reporting/snapshots/rebuild' => 'settings.manage',
        'POST api/v1/staff/cashier/shifts/open' => 'cashier.shift.manage',
        'POST api/v1/staff/cashier/shifts/{shift_id}/close' => 'cashier.shift.manage',
        'POST api/v1/staff/conversations/{conversation_id}/assign' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/internal-notes' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/links' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/outbound-replies' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/take-over' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/unassign' => 'conversation.manage',
        'POST api/v1/staff/conversations/{conversation_id}/workflow-state' => 'conversation.manage',
        'POST api/v1/staff/finance/invoices/{reservation_id}/issue' => 'settlement.manage',
        'POST api/v1/staff/kitchen/tickets/{ticket_id}/bump' => 'kitchen.manage',
        'POST api/v1/staff/kitchen/tickets/{ticket_id}/fire' => 'kitchen.manage',
        'POST api/v1/staff/kitchen/tickets/{ticket_id}/recall' => 'kitchen.manage',
        'POST api/v1/staff/orders/{order_id}/bill-snapshot' => 'order.manage',
        'POST api/v1/staff/orders/{order_id}/checkout' => 'settlement.manage',
        'POST api/v1/staff/orders/{order_id}/close' => 'order.manage',
        'POST api/v1/staff/orders/{order_id}/items' => 'order.manage',
        'POST api/v1/staff/orders/{order_id}/items/{order_item_id}/status' => 'order.manage',
        'POST api/v1/staff/orders/{order_id}/kitchen/dispatch' => 'order.manage',
        'POST api/v1/staff/orders/{order_id}/pay' => 'settlement.manage',
        'POST api/v1/staff/orders/{order_id}/settlement/finalize' => 'settlement.manage',
        'POST api/v1/staff/reservations/{id}/assign-best-fit' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/assign-table' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/check-in' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/move-table' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/reschedule' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/timeline/actions/assign-best-fit' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/timeline/actions/assign-suggested' => 'reservation.manage',
        'POST api/v1/staff/reservations/{id}/timeline/actions/check-in' => 'reservation.manage',
        'POST api/v1/staff/reservations/{reservation_id}/deposit/pay' => 'settlement.manage',
        'POST api/v1/staff/reservations/{reservation_id}/loyalty/redeem' => 'loyalty.redeem',
        'POST api/v1/staff/reservations/{reservation_id}/loyalty/redeem/release' => 'loyalty.redeem',
        'POST api/v1/staff/reservations/{reservation_id}/loyalty/release' => 'loyalty.redeem',
        'POST api/v1/staff/reservations/{reservation_id}/refund' => 'payment.refund',
        'POST api/v1/staff/reservations/{reservation_id}/refund-cancel' => 'payment.refund',
        'POST api/v1/staff/reservations/{reservation_id}/voucher/apply' => 'voucher.manage',
        'POST api/v1/staff/reservations/{reservation_id}/voucher/release' => 'voucher.manage',
        'POST api/v1/staff/reservations/{reservation_id}/voucher/remove' => 'voucher.manage',
        'POST api/v1/staff/service-sessions/walk-in' => 'reservation.manage',
        'POST api/v1/staff/tables/{table_id}/orders' => 'order.manage',
        'POST api/v1/staff/tables/{table_id}/release' => 'table.release',
        'POST api/v1/staff/users/{user_id}/loyalty/adjust' => 'loyalty.adjust',
        'POST api/v1/staff/waiting-list' => 'waiting_list.manage',
        'POST api/v1/staff/waiting-list/{id}/advance' => 'waiting_list.manage',
        'POST api/v1/staff/waiting-list/{id}/cancel' => 'waiting_list.manage',
        'POST api/v1/staff/waiting-list/{id}/notify' => 'waiting_list.manage',
        'POST api/v1/staff/waiting-list/{id}/seat' => 'waiting_list.manage',
        'PUT api/v1/admin/inventory/menu-items/{id}/recipe' => 'inventory.manage',
        'PUT api/v1/admin/kitchen/stations/{station_id}/category-routes' => 'settings.manage',
        'PUT api/v1/admin/menu/prices/{price_id}' => 'menu.manage',
    ],

    'route_aliases' => [
        'GET api/v1/staff/table-board' => 'GET api/v1/staff/tables/board',
        'POST api/v1/staff/orders/{order_id}/checkout' => 'POST api/v1/staff/orders/{order_id}/settlement/finalize',
        'POST api/v1/staff/orders/{order_id}/close' => 'POST api/v1/staff/orders/{order_id}/bill-snapshot',
        'POST api/v1/staff/reservations/{reservation_id}/loyalty/release' => 'POST api/v1/staff/reservations/{reservation_id}/loyalty/redeem/release',
        'POST api/v1/staff/reservations/{reservation_id}/voucher/release' => 'POST api/v1/staff/reservations/{reservation_id}/voucher/remove',
    ],

    'capability_aliases' => [
        'order.manage' => [
            'kitchen.manage',
        ],
        'ops.view' => [
            'ops.health.view',
            'ops.metrics.view',
            'ops.release.view',
        ],
        'settlement.manage' => [
            'cashier.shift.manage',
            'reporting.view',
        ],
    ],

    'messages' => [
        'default' => 'Resolved staff actor is not allowed to perform this operation.',
        'branch_scope_denied' => 'Resolved staff actor is not allowed to operate on the selected branch.',
        'unknown_capability' => 'Staff capability contract is not registered.',
    ],
];
