server {
    listen 80;
    server_name api.yourdomain.com; # TODO: replace with real domain

    # Protect sensitive files
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.yourdomain.com; # TODO: replace with real domain

    ssl_certificate /etc/nginx/certs/live/api.yourdomain.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/api.yourdomain.com/privkey.pem;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    location ~ /\.(?!well-known).* {
        deny all;
    }
    location = /.env {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    error_page 404 /index.php;
}
