server {
    listen 80;
    server_name mocsen-bistro.ddns.net;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name mocsen-bistro.ddns.net;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/mocsen-bistro.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mocsen-bistro.ddns.net/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
